on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install newman and newman-reporter-allure
        run: |
          npm install -g newman newman-reporter-allure
          echo "Newman and newman-reporter-allure installed."
      
      - name: Run Postman tests
        if: always()
        continue-on-error: true
        run: |
          newman run Postmans-Collections/Postmans-Collections.json --reporters cli,allure --reporter-allure-export=allure-results
          echo "Postman tests completed."

      - name: Generate Allure Report
        id: build
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        id: deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
